spring:
  application:
    name: escola-api
  datasource:
    url: jdbc:postgresql://localhost:5432/escola-api
    username: ${DB_USERNAME:miguel}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 500

jwt:
  secret: ${JWT_SECRET}

regras-negocio:
  max-alunos-por-curso: 100
  max-cursos-por-professor: 5
  max-professores-por-curso: 5